# Generated by Django 4.2.30 on 2026-05-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Savol')),
                ('question_uz', models.CharField(max_length=500, null=True, verbose_name='Savol')),
                ('question_ru', models.CharField(max_length=500, null=True, verbose_name='Savol')),
                ('question_en', models.CharField(max_length=500, null=True, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('answer_uz', models.TextField(null=True, verbose_name='Javob')),
                ('answer_ru', models.TextField(null=True, verbose_name='Javob')),
                ('answer_en', models.TextField(null=True, verbose_name='Javob')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Savol-Javob',
                'verbose_name_plural': 'Savol-Javoblar',
                'ordering': ['order'],
            },
        ),
    ]



